import { CalendarDays } from 'lucide-react';
import { useFetch, PageError, PageLoader } from '../../hooks/useFetch';
import * as flowdeskApi from '../../services/flowdeskApi';
import { Card, EmptyState, PageHeader } from '../components/shared';

export default function CalendarPage() {
  const { data, loading, error, reload } = useFetch(() => flowdeskApi.getTasks(), [], []);

  if (loading) return <PageLoader message="Loading calendar tasks..." />;
  if (error) return <PageError message={error} onRetry={reload} />;

  const tasks = data || [];
  const datedTasks = tasks.filter((item) => item.dueDate);
  return (
    <div className="space-y-5">
      <PageHeader title="Calendar" subtitle="Upcoming due dates generated by active tasks." />
      {datedTasks.length === 0 ? (
        <EmptyState title="No dated tasks" description="Task deadlines with due dates will appear in this timeline." />
      ) : (
        <Card className="space-y-2">
          {datedTasks.map((task) => (
            <div key={task.id} className="flex items-center justify-between rounded-lg border border-slate-200 p-3 text-sm dark:border-slate-800">
              <div className="flex items-center gap-2">
                <CalendarDays size={15} className="text-blue-600" />
                <p className="font-medium">{task.title || task.name || task.id}</p>
              </div>
              <p className="text-slate-500">{new Date(task.dueDate).toLocaleDateString()}</p>
            </div>
          ))}
        </Card>
      )}
    </div>
  );
}
