import { CheckSquare, Plus, Square } from 'lucide-react';
import { useState } from 'react';
import { useFetch, PageError, PageLoader } from '../../hooks/useFetch';
import * as flowdeskApi from '../../services/flowdeskApi';
import {
  Badge, Btn, Card, EmptyState, FilterTabs, Modal, PageHeader, RelativeTime,
  SearchInput, inputCls, labelCls, selectCls,
} from '../components/shared';
import { usePermissions } from '../permissions';

const STATUS_TABS = [
  { value: 'all',       label: 'All' },
  { value: 'pending',   label: 'Pending' },
  { value: 'in_progress', label: 'In Progress' },
  { value: 'completed', label: 'Completed' },
];

function CreateTaskModal({ onClose, onCreated }) {
  const [form, setForm] = useState({ title: '', description: '', dueDate: '', assignee: '' });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  async function submit(e) {
    e.preventDefault();
    setBusy(true);
    setError('');
    try {
      await flowdeskApi.createTask({
        title: form.title,
        description: form.description || undefined,
        dueDate: form.dueDate || undefined,
        assignee: form.assignee || undefined,
      });
      onCreated();
      onClose();
    } catch (err) {
      setError(err.message || 'Failed to create task');
    } finally {
      setBusy(false);
    }
  }

  return (
    <Modal open onClose={onClose} title="Create Task">
      <form onSubmit={submit} className="grid gap-4">
        <label className={labelCls}>
          Title *
          <input className={inputCls} value={form.title} onChange={(e) => setForm((p) => ({ ...p, title: e.target.value }))} required />
        </label>
        <label className={labelCls}>
          Description
          <textarea className={inputCls} rows={3} value={form.description} onChange={(e) => setForm((p) => ({ ...p, description: e.target.value }))} />
        </label>
        <label className={labelCls}>
          Assignee (email or name)
          <input className={inputCls} value={form.assignee} onChange={(e) => setForm((p) => ({ ...p, assignee: e.target.value }))} />
        </label>
        <label className={labelCls}>
          Due Date
          <input type="date" className={inputCls} value={form.dueDate} onChange={(e) => setForm((p) => ({ ...p, dueDate: e.target.value }))} />
        </label>
        {error ? <p className="text-sm text-rose-600">{error}</p> : null}
        <div className="flex justify-end gap-2">
          <Btn type="button" variant="secondary" onClick={onClose} disabled={busy}>Cancel</Btn>
          <Btn type="submit" disabled={busy}>{busy ? 'Creating…' : 'Create task'}</Btn>
        </div>
      </form>
    </Modal>
  );
}

export default function TasksPage() {
  const { can } = usePermissions();
  const canCreate = can('createTask');

  const [showCreate, setShowCreate] = useState(false);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [completing, setCompleting] = useState(null);

  const { data, loading, error, reload } = useFetch(() => flowdeskApi.getTasks(), [], []);

  async function markComplete(taskId) {
    setCompleting(taskId);
    try {
      await flowdeskApi.completeTask(taskId);
      reload();
    } catch {}
    setCompleting(null);
  }

  if (loading) return <PageLoader message="Loading tasks…" />;
  if (error) return <PageError message={error} onRetry={reload} />;

  const tasks = (data || []).filter((t) => {
    const q = search.toLowerCase();
    const matchSearch = !q || (t.title || '').toLowerCase().includes(q) || (t.assigneeName || t.assignee || '').toLowerCase().includes(q);
    const matchStatus = statusFilter === 'all' || (t.status || 'pending') === statusFilter;
    return matchSearch && matchStatus;
  });

  const total = (data || []).length;
  const completed = (data || []).filter((t) => t.status === 'completed').length;

  return (
    <div className="space-y-5">
      <PageHeader
        title="Tasks"
        subtitle="Operational checklist generated by workflow engines and team leads."
        actions={
          canCreate ? (
            <Btn onClick={() => setShowCreate(true)}>
              <Plus size={15} /> New task
            </Btn>
          ) : null
        }
      />

      {/* Summary */}
      <div className="flex items-center gap-4 text-sm text-slate-500">
        <span><span className="font-semibold text-slate-900 dark:text-slate-100">{total}</span> total tasks</span>
        <span><span className="font-semibold text-emerald-600">{completed}</span> completed</span>
        <span><span className="font-semibold text-amber-600">{total - completed}</span> pending</span>
      </div>

      {/* Toolbar */}
      <div className="flex flex-wrap items-center gap-3">
        <FilterTabs options={STATUS_TABS} value={statusFilter} onChange={setStatusFilter} />
        <SearchInput className="max-w-xs ml-auto" value={search} onChange={setSearch} placeholder="Search tasks…" />
      </div>

      {tasks.length === 0 ? (
        <EmptyState
          title="No tasks available"
          description="Tasks are generated when workflows require action or you create them manually."
          action={canCreate ? <Btn onClick={() => setShowCreate(true)}><Plus size={15} />Create task</Btn> : null}
        />
      ) : (
        <div className="space-y-2">
          {tasks.map((task) => {
            const isDone = task.status === 'completed';
            const isCompletingThis = completing === task.id;
            return (
              <Card key={task.id} className={`flex flex-wrap items-center justify-between gap-3 ${isDone ? 'opacity-60' : ''}`}>
                <div className="flex items-start gap-3 min-w-0 flex-1">
                  <button
                    onClick={() => !isDone && markComplete(task.id)}
                    disabled={isDone || isCompletingThis}
                    className="mt-0.5 flex-shrink-0 text-slate-400 transition hover:text-emerald-500 disabled:cursor-default"
                    title={isDone ? 'Completed' : 'Mark complete'}
                  >
                    {isDone ? <CheckSquare size={18} className="text-emerald-500" /> : <Square size={18} />}
                  </button>
                  <div className="min-w-0">
                    <p className={`font-medium ${isDone ? 'line-through text-slate-500' : ''}`}>{task.title || task.name || task.id}</p>
                    <p className="text-sm text-slate-500">{task.assigneeName || task.assignee || 'Unassigned'}</p>
                    {task.description && <p className="mt-1 text-xs text-slate-400 line-clamp-1">{task.description}</p>}
                  </div>
                </div>
                <div className="flex items-center gap-3 flex-shrink-0 text-sm">
                  <Badge tone={task.status || 'pending'}>{task.status || 'pending'}</Badge>
                  {task.dueDate ? (
                    <span className={`text-xs ${new Date(task.dueDate) < new Date() && !isDone ? 'text-rose-500 font-medium' : 'text-slate-500'}`}>
                      Due {new Date(task.dueDate).toLocaleDateString()}
                    </span>
                  ) : (
                    <span className="text-xs text-slate-400">No due date</span>
                  )}
                </div>
              </Card>
            );
          })}
        </div>
      )}

      {showCreate && <CreateTaskModal onClose={() => setShowCreate(false)} onCreated={reload} />}
    </div>
  );
}
