import { CheckSquare } from 'lucide-react';
import { useFetch, PageError, PageLoader } from '../../hooks/useFetch';
import * as flowdeskApi from '../../services/flowdeskApi';
import { Badge, Card, EmptyState, PageHeader } from '../components/shared';

export default function TasksPage() {
  const { data, loading, error, reload } = useFetch(() => flowdeskApi.getTasks(), [], []);

  if (loading) return <PageLoader message="Loading tasks..." />;
  if (error) return <PageError message={error} onRetry={reload} />;

  const tasks = data || [];
  return (
    <div className="space-y-5">
      <PageHeader title="Tasks" subtitle="Operational checklist generated by workflow engines." />
      {tasks.length === 0 ? (
        <EmptyState title="No tasks available" description="Tasks are generated when active workflows require action." />
      ) : (
        <Card className="space-y-3">
          {tasks.map((task) => (
            <div key={task.id} className="flex flex-wrap items-center justify-between rounded-lg border border-slate-200 p-3 text-sm dark:border-slate-800">
              <div>
                <p className="font-medium">{task.title || task.name || task.id}</p>
                <p className="text-slate-500">{task.assigneeName || task.assignee || 'Unassigned'}</p>
              </div>
              <div className="flex items-center gap-2">
                <Badge tone={task.status}>{task.status || 'pending'}</Badge>
                <span className="text-xs text-slate-500">{task.dueDate ? new Date(task.dueDate).toLocaleDateString() : 'No due date'}</span>
              </div>
            </div>
          ))}
        </Card>
      )}
      <p className="inline-flex items-center gap-2 text-sm text-slate-500">
        <CheckSquare size={15} />
        Active tasks: {tasks.length}
      </p>
    </div>
  );
}
